### PR TITLE
llvm-10.0: include riscv64 support

### PR DESCRIPTION
**Pull request by rebeccasf**
LLVM has support for riscv64 architecture. These changes are meant to ensure building swiftshader for riscv64 is possible for a start.

### CODE REVIEW

**Comment by rebeccasf** [comment]
Managed to push commits into Gerrit. Will close this for now.
Please refer to Gerrit:
https://swiftshader-review.googlesource.com/c/SwiftShader/+/64669
https://swiftshader-review.googlesource.com/c/SwiftShader/+/64670

**Comment by ericcurtin** [comment]
Hi @rebeccasf how did you manage to push, I'm struggling with the push part, what is username/password or how do you import ssh keys etc.? I signed CLA and have an account, but the push doesn't seem to work. Wondering what I'm doing wrong?

**Comment by ben-clayton** [comment]
@ericcurtin - you need to install the gitcookies from https://swiftshader-review.googlesource.com/settings/#HTTPCredentials.

See:

---

Click: HTTP Credentials [Obtain password](https://swiftshader-review.googlesource.com/new-password) (opens in a new tab)

---

**Comment by ericcurtin** [comment]
Thanks very much @ben-clayton @c0d1f1ed also sent me an email. I got something pushed here:

https://swiftshader-review.googlesource.com/c/SwiftShader/+/66268

**Pull request closed without merging**
